function [sample, measurement] = getCOAData(conn, samplenumber) 

sql = "SELECT p.name_coa Grade, q.longname TechnicalGrade, s.customer Customer, s.ordernumber_PVS,  " + ...
    "s.ordernumber_client,substring(s.loadingDate,1,10) SampleDate, p.bruto Bruto, " + ...
    "substring(s.TestDate,1,10) TestDate, s.BatchNumber, s.ContainerNumber, s.onedecimal " + ...
    " FROM sample s, product p, quality q  " + ...
    " WHERE samplenumber='%s' and s.product_id=p.id  and s.quality_id=q.id" ; 

sql = sprintf( sql, samplenumber ) ; 
sample = select( conn, sql ) ; 

sql = "SELECT v.Test, v.Element, m.value TestResults, " + ...
    "iif(m.min is null, '', cast(m.min as char)) Min, " + ...
    "iif(m.max is null, '', cast(m.max as char)) Max," + ...
    "v.unit, m.less, v.typevar, m.listvalue  " + ...
    "FROM sample s, measurement m, variable v " + ...
" WHERE m.sample_id=s.id and m.variable_id=v.id and samplenumber='%s' ORDER BY v.ord; " ; 
sql = sprintf( sql, samplenumber ) ; 
%tt = select( conn, sql ) ; 
measurement = select( conn, sql ) ; 

return 