function sample = getCOCData(conn, samplenumber) 

sql = "SELECT p.name Grade, q.longname TechnicalGrade, s.customer Customer, s.ordernumber_PVS,  " + ...
    "s.ordernumber_client,substring(s.Date,1,10) SampleDate, p.bruto Bruto, " + ...
    " substring(s.creationDate,1,10) TestDate, s.BatchNumber, s.ContainerNumber," + ...
    " sp.TDS " + ...
    " FROM sample s , spec sp, product p, quality q  " + ...
    " WHERE samplenumber='%s' and s.product_id=p.id  and s.quality_id=q.id" + ...
    " and sp.product_id=s.product_id and sp.quality_id=s.quality_id  and sp.typeSpec='GEN'" ; 

sql = sprintf( sql, samplenumber ) ; 
sample = select( conn, sql ) ; 


end 