function data = getMeasurementList(conn, idsample) 

sql = "SELECT v.shortname name, variable_id, min, max, 1 flag, v.ord   " + ...
    " FROM measurement m, variable v " + ...
    " WHERE sample_id = %d and m.variable_id=v.id   " + ...
    " UNION " + ...
    " SELECT v.shortname, variable_id, min, max, 0 flag, v.ord  " + ...
    " FROM dspec d,  spec s, sample ss, variable v  " + ...
    " WHERE s.product_id=ss.product_id and s.quality_id=ss.quality_id and s.typeSpec='GEN' " + ...
    " and ss.id = %d and d.spec_id = s.id and d.variable_id=v.id and  not " + ...
    " exists( SELECT * FROM measurement m where m.sample_id = %d and " + ...
    "m.variable_id = d.variable_id )  ORDER BY ord" ;

sql = sprintf(sql, [idsample, idsample, idsample]) ; 
T = select(conn, sql) ; 
data= table( T.name, T.flag, T.min, T.max , T.variable_id) ; 
data.Properties.VariableNames{1} = 'Variable';
data.Properties.VariableNames{2} = 'Flag';
data.Properties.VariableNames{3} = 'Min';
data.Properties.VariableNames{4} = 'Max';
data.Properties.VariableNames{5} = 'variable_id';

end