function data = getMeasurementListPQ(conn, idSamplePoint, idProduct, idQuality) 

idProduct = string(idProduct) ; 
idQuality = string(idQuality) ; 
idSamplePoint = string(idSamplePoint) ;

sql = "SELECT v.shortname, d.variable_id, min, max, 0 flag, d2.ord " + ... 
"FROM dspec d,  spec s,  variable v, dsamplematrix d2,  samplematrix s2  " + ...
"WHERE s.product_id=s2.product_id and s.quality_id=s2.quality_id  " + ...
"and s.typeSpec='GEN'  and d.spec_id = s.id  and d.variable_id=v.id  " + ...
"and d2.samplematrix_id = s2.id  and d2.variable_id=v.id  and s.product_id=%s  " + ...
"and s.quality_id=%s and s2.samplepoint_id=%s  " + ...
"UNION   " + ...
"SELECT v.shortname, variable_id, min, max, 0 flag, 0 ord " + ...    
"FROM dspec d,  spec s,  variable v  " + ...
"WHERE s.product_id=%s  and s.quality_id=%s and s.typeSpec='GEN' and d.spec_id = s.id  " + ...
"and d.variable_id=v.id  " + ...
"and not v.id in (SELECT d2.variable_id " + ...
"FROM dspec d,  spec s, dsamplematrix d2,  samplematrix s2 " + ... 
"WHERE s.product_id=s2.product_id and s.quality_id=s2.quality_id " + ... 
"and s.typeSpec='GEN'  and d.spec_id = s.id  and d.variable_id=d2.variable_id " + ...
"and d2.samplematrix_id = s2.id and s.product_id=%s " + ...
"and s.quality_id=%s and s2.samplepoint_id=%s) " + ...
"UNION " + ...
"SELECT v.shortname, d2.variable_id, null min, null max, 0 flag, d2.ord  " + ...
"FROM variable v, dsamplematrix d2,  samplematrix s2  " + ...
"WHERE d2.samplematrix_id = s2.id  and d2.variable_id=v.id  and s2.product_id=%s " + ...
"and s2.quality_id=%s and s2.samplepoint_id=%s  " + ...
"and not v.id in ( SELECT d.variable_id  " + ...
"FROM dspec d,  spec s " + ...
"WHERE s.product_id=s2.product_id and s.quality_id=s2.quality_id  " + ...
"and s.typeSpec='GEN' and d.spec_id = s.id ) " + ...
"ORDER BY ord desc" ; 
sql = sprintf(sql,  idProduct, idQuality, idSamplePoint, idProduct, ...
    idQuality, idProduct, idQuality, idSamplePoint, idProduct, ...
    idQuality, idSamplePoint ) ; 

T = select(conn, sql) ; 
data= table( T.shortname, T.flag, T.min, T.max , T.variable_id) ; 
data.Properties.VariableNames{1} = 'Variable';
data.Properties.VariableNames{2} = 'Flag';
data.Properties.VariableNames{3} = 'Min';
data.Properties.VariableNames{4} = 'Max';
data.Properties.VariableNames{5} = 'variable_id';

end